name: CI

on:
  repository_dispatch:
    types: [release]

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - name: Release
        if: contains(github.event.action, 'release')
        run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
